In [1]:
import numpy as np

In [2]:
"""WAP in  to find the degree of an polynomial."""

terms=int(input("Enter the number of terms, including constant term."))
x=[]
coeff=[]
while terms>0:
  x.append(int(input("Enter the exponent:")))
  coeff.append(int(input("Enter the coefficient:")))
  terms=terms-1

print("The equation is:")

for i in range(len(x)):
  if (i==len(x)-1):
    print(f"{coeff[i]}x^{x[i]}",end='')
  else:
    print(f"{coeff[i]}x^{x[i]}+",end='')

x=sorted(x,reverse=True)
print(f"\nThe degree of the equation is:{x[0]}")

print("Using NumPy:")
pol = np.poly1d([7,2,4,1])  
print ("Degree of Polynomial: ", pol.order) 

list1=[2,2,4,5,6]
polyNew = np.poly1d(list1)
print ("Degree of Polynomial: ", (len(list1)-1))

Enter the number of terms, including constant term.3
Enter the exponent:0
Enter the coefficient:3
Enter the exponent:2
Enter the coefficient:4
Enter the exponent:1
Enter the coefficient:5
The equation is:
3x^0+4x^2+5x^1
The degree of the equation is:2
Using NumPy:
Degree of Polynomial:  3
Degree of Polynomial:  4


In [3]:
"""WAP to find roots of a Quadratic Equation"""
import math  

a =int(input("Enter term for a:"))
b =int(input("Enter term for b:"))
c =int(input("Enter term for c:"))

  
d = b * b - 4 * a * c  
sqrt_val = math.sqrt(abs(d))  
      
   
if d > 0:  
  print("Roots are real and different.")  
  print((-b + sqrt_val)/(2 * a))  
  print((-b - sqrt_val)/(2 * a))  
      
elif d == 0:  
  print("Roots are real and equal.")  
  print(-b / (2 * a))  
      
else: 
  print("Roots are complex")  
  print(- b / (2 * a), " + i", sqrt_val)  
  print(- b / (2 * a), " - i", sqrt_val)  

print("Using NumPy:")
quad = [1, 2, 1]
print('Roots of equation: ',np.roots(quad))

Enter term for a:1
Enter term for b:2
Enter term for c:1
Roots are real and equal.
-1.0
Using NumPy:
Roots of equation:  [-1. -1.]


In [5]:
"""WAP to print diagonal elements of a matrix."""
n = 4
a = [[ 1, 2, 3, 4 ],
     [ 5, 6, 7, 8 ],
     [ 1, 2, 3, 4 ],
     [ 5, 6, 7, 8 ]]

for i in range(n):
  for j in range(n):
    if (i == j):
      print(a[i][j], end = ", ")
print("Using NumPy:")
mat=np.matrix(a)
print('Diagonal Elements of Matrix: ',mat.diagonal())

1, 6, 3, 8, Using NumPy:
Diagonal Elements of Matrix:  [[1 6 3 8]]


In [6]:
"""WAP to find factorial of a number."""
x=int(input("Enter the number:"))
t=1
for i in range(1,x+1):
  t=t*i

print(f"Factorial of {x} is:{t}")
print("Using NumPy:")
print(np.math.factorial(x))

Enter the number:5
Factorial of 5 is:120
Using NumPy:
120


In [7]:
"""WAP to find profit or loss for a given CP and SP."""
CP = float(input(" Please Enter the Cost Price of the product: "))

SP = float(input(" Please Enter the Sale Price of the product: "))

if(CP > SP):

   amount = CP - SP

   print("Total Loss Amount = {0}".format(amount))

elif(SP > CP):

   amount = SP - CP

   print("Total Profit = {0}".format(amount))

else:

   print("There is no profit no loss.")

 Please Enter the Cost Price of the product: 1234.22
 Please Enter the Sale Price of the product: 1050.75
Total Loss Amount = 183.47000000000003


In [8]:
"""WAP to sort the matrix row wise and column wise."""
a= [[9, 8, 7, 1 ],[7, 3, 0, 2],[9, 5, 3, 2],[ 6, 3, 1, 2 ]]

a=np.array(a)

print ("Row-wise sorted array:\n",np.sort(a, axis = 0)) 
print ("Column-wise sorted array:\n",np.sort(a, axis = 1)) 

Row-wise sorted array:
 [[6 3 0 1]
 [7 3 1 2]
 [9 5 3 2]
 [9 8 7 2]]
Column-wise sorted array:
 [[1 7 8 9]
 [0 2 3 7]
 [2 3 5 9]
 [1 2 3 6]]
